### ISSUE TITLE
Add support for TLS certificate authentication

### ISSUE THREAD

**Issue by ghost** [BetterCloud/vault-java-driver#26]
Vault allows authentication using SSL/TLS client certificates:
https://www.vaultproject.io/docs/auth/cert.html
Are there any plans to add support for this auth backend in this client/driver?

**Comment by ejnsilva** [comment]
I have implemented this in
https://github.com/BetterCloud/vault-java-driver/pull/44

**Comment by salyh** [comment]
Is there a expected release date/version for this feature?

**Comment by steve-perkins** [comment]
Apologies for the delay there.  We received a pull request back in January (see above), but there was a fair amount of code review feedback and we never heard back from the submitter either way.

I'll see about carving off some time in the next week to take a look at this.  Whether that means merging @ejnsilva 's PR and then making any changes afterward, or starting from a blank slate and implementing it myself.  Since this issue has been open so long, I don't mind putting out a patch version of the driver that includes only this update.

**Comment by djdoeslinux** [comment]
This would be greatly appreciated. This is the only missing feature from this project that prevents me from using the mainline release.

**Comment by steve-perkins** [comment]
I just wanted to give an update that this is now actively being worked on.  There was an earlier PR dealing with it... but that PR had some issues, and no test coverage or documentation, and the original author seems to have abandoned it.  So I've taken up implementing this myself.

Originally, a challenge was the sheer amount of manual setup that would be necessary to run the tests against a Vault test server with SSL enabled.  You need to create your own CA, make the cert and key available in both Vault-friend PEM format and Java-friendly JKS format, etc.  Then the Vault "dev mode" doesn't support SSL anyway, so you have to get into standing up a full-fledged server instance (which leads to yet more required steps).  It was a lot more than I was comfortable forcing into the README.md for setting up an integration test environment.

However, last week I finished migrating over the integration test suite to instead be Docker-based.  So now the test suite itself stands up and automatically configures a Docker-hosted Vault server for you, with no manual steps (hooray!).  I just finished the process of getting a "real" Vault server working, rather than "dev mode", making SSL testing possible.

I'm a couple more breakthroughs away from having basic SSL working, and adding support for client auth.  Sadly, I only get to work on this using scraps of time in between job-related projects (as my company doesn't necessarily need this functionality internally).  So I can't promise an exact timeframe, but I hope to be close to a 3.0.0 release soon.

**Comment by djdoeslinux** [comment]
I'm happy to contribute my time/effort if there is work you think can be easily carved off.

**Comment by steve-perkins** [comment]
Sadly, I don't think the remaining work is really all that divisible.  However, you're welcome to check out the `tls-client-auth` branch to see the current state of progress.  

I just got basic HTTPS connectivity up and running in the integration test suite, which required solving at least a dozen interesting challenges.  Now that basic SSL is in place, I don't anticipate the addition of client auth to be as bad.

**Comment by steve-perkins** [comment]
Support for authentication through Vault's TLS Certificate auth backend has now been merged into `master`, via pull request #59!

If anyone wishes to clone master, and build and test the `3.0.0-SNAPSHOT` version that it represents, then it would be very much appreciated.  We do no use the TLS Certificate auth backend ourselves, so all testing has pretty much been limited to the integration test suite.

I have a couple of misc bug reports that I'd still like to look into, but otherwise I hope to get a `3.0.0` release pushed up to Maven Central next week.

**Comment by steve-perkins** [comment]
Version 3.0.0 has now been pushed to Maven Central, with this functionality.  It should be indexed in Maven Central within the next few hours.
