### ISSUE TITLE
Maven central lacks latest version 1.2.0

### ISSUE THREAD

**Issue by landpro** [BetterCloud/vault-java-driver#31]

**Comment by landpro** [comment]
Please cut off the release if it is ready

**Comment by steve-perkins** [comment]
My hope is to release 1.2.0 tomorrow, it's basically ready.  However, I'm waiting to hear back from @alexku-o on https://github.com/BetterCloud/vault-java-driver/issues/27... to see if they're going to have a pull request for this release, or whether it need to hold off until version 2.0.0 (which will follow shortly).

**Comment by landpro** [comment]
Thank you vm for the good news.

Your library is great! Integrated with our spring application within 2 hours yesterday. And this after spending days with spring-cloud-vault-config which has a number of issues.

**Comment by steve-perkins** [comment]
Thanks, Alexander!  I'd be interested to hear more details about the issues
you've seen with spring-cloud-vault-config, either in this thread or
offline (steve.perkins@bettercloud.com).

We've been taking a look at Spring Cloud Config and Spring Cloud Stream
(using Vault indirectly).  Since all of these things are still very new, it
would be super helpful to have a heads up on problems that others have seen.

**Comment by steve-perkins** [comment]
1.2.0 is now up on Maven Central
