### ISSUE TITLE
Use 'java-test-containers' for Integration Tests

### ISSUE THREAD

**Issue by MyRealityCoding** [BetterCloud/vault-java-driver#36]
Right now the integration tests expect a locally running Vault server and particular environment variables set. By using [java-test-containers](https://github.com/testcontainers/testcontainers-java) a Docker container is created when running the tests, all integration tests are running against a Vault dev server running in Docker. After all tests have run the container will be destroyed automatically.

**Comment by MyRealityCoding** [comment]
Currently blocked. PR: https://github.com/BetterCloud/vault-java-driver/pull/25

**Comment by steve-perkins** [comment]
There is already a PR for this (see above).  There is currently no timeline for merging that PR, because:

1. The solution doesn't support development on Windows, and we're not willing to drop that capability just to make running the test suite slightly easier.

1. The solution only supports Java 8+, and we're not willing to drop Java 7 support at least until Java 9 ships.

**Comment by MyRealityCoding** [comment]
Why it does not support development on Windows? There is already a stable Docker Client for Windows available. (at least it works on my machine flawless)

**Comment by steve-perkins** [comment]
Shrug... maybe it happens to work for you, but they state very explicitly that Docker on Windows is either unsupported or untested. Lack of Java 7 compatibility would be a deal-breaker for now, regardless.
