### ISSUE TITLE
need aws-ec2 auth support

### ISSUE THREAD

**Issue by maksimlikharev** [BetterCloud/vault-java-driver#48]
In order to work with ec2 roles, it needs a new auth method as it require different parameters, `pkcs7` and `nonce`

**Comment by maksimlikharev** [comment]
unfortunately I cannot subclass and implement that by my own as well, due to 

`private final VaultConfig config;`

**Comment by steve-perkins** [comment]
If you implement this in another fork, then I'd be more than happy to look at it as a pull request.  If so, then you might want to wait a day or two until the `tls-client-auth` branch gets merged back into `master`, as there is a lot going on within that branch.

Otherwise, this almost certainly wouldn't get on the radar until after the `3.0.0` release goes out.  The most troublesome part would be test coverage.  We're in a much better place now that the test suite uses a "real" Vault instance in a Docker container, rather than a "dev mode" instance requiring a lot of manual setup.  Even so, I'm not sure how you can test auth backends which use a 3rd-party service (i.e. AWS, GitHub, etc) without having a public instance of that 3rd-party service to test against.  

Internally, our company uses Google Cloud Platform... so I don't even have an AWS environment to test against privately, outside of the test suite that's hosted within this repo.

**Comment by rohit2g** [comment]
@steve-perkins Does this track IAM auth as well?

**Comment by steve-perkins** [comment]
I believe this is duplicated by issue #89, which has an associated pull request and is target for the next release.  If I'm missing anything in this issue that is not captured by that other one, please let me know and I'll re-open!
