### ISSUE TITLE
Any plans to support token renew?

### ISSUE THREAD

**Issue by jentfoo** [BetterCloud/vault-java-driver#5]
A feature that would be very useful to us would be `/auth/token/renew-self`.  Is there any interest or plans to include this?

I would be willing to help with a PR if necessary, but it looked like a new type of API request (and so I am not sure how exactly you would want it to fit into the library).  Would it make sense to make this accessible from `Logical`?

**Comment by steve-perkins** [comment]
Yup, we'd like to eventually reach parity with the Ruby driver (or at least as close as it makes sense).

Offhand, I'd imagine that this would hang off `Auth` rather than `Logical`.  If it's okay, I'd like to talk with the developer who worked on that piece.  He's out on paternity leave with a new baby this week, but I believe he's coming back next week.  Depending on that feedback, we'll either put on the roadmap or just discuss a PR if you're interested.

Thanks!

**Comment by jentfoo** [comment]
> Depending on that feedback, we'll either put on the roadmap or just discuss a PR if you're interested.

Sounds good, just let me know.  This functionality is important to us, so if you are not able to get to it (or give me guidance on how it should look so I can PR a solution) reasonably soon we may have to adjust our usage.

**Comment by steve-perkins** [comment]
Dev-complete... going out with the next release.

**Comment by jentfoo** [comment]
Awesome, thank you!

**Comment by steve-perkins** [comment]
This just went out with version 1.0.0.  It may take a few hours for Maven Central to sync and list it.
