### ISSUE TITLE
failure to open connection leaks a resource?

### ISSUE THREAD

**Issue by n8leon** [BetterCloud/vault-java-driver#57]
Is it possible that a resource gets leaked when the code fails to open a new connection?

e.g. in this code:
https://github.com/BetterCloud/vault-java-driver/blob/master/src/main/java/com/bettercloud/vault/rest/Rest.java#L403

I'm thinking it would be good form to have a finally{} block that releases the connection resource if it is not null?
i.e. calls disconnect()

Thanks,
Nate

**Comment by steve-perkins** [comment]
Thanks!  I'll take a look at this next week, before putting together the `3.0.0` release for Maven Central.

Just wanting to confirm that the line you're talking about is currently:

https://github.com/BetterCloud/vault-java-driver/blob/master/src/main/java/com/bettercloud/vault/rest/Rest.java#L417

The line numbers are thrown off a bit, due to a PR that was recently merged.

**Comment by n8leon** [comment]
👍

**Comment by steve-perkins** [comment]
Version 3.0.0 has been released to Maven Central, with this change.  It should be indexed in Maven Central within the next few hours.

**Comment by kilokahn** [comment]
@steve-perkins - is there any appetite to porting this fix to the 2.x series as well? Thanks!
