### ISSUE TITLE
Please make less classes 'final'

### ISSUE THREAD

**Issue by jentfoo** [BetterCloud/vault-java-driver#6]
This makes it very difficult to unit test.  It can be impossible to mock out the library, instead requiring the user to wrap every type in their own types so that they can be mocked out.

**Comment by jentfoo** [comment]
Sorry for submitting before adding a description (finger slipped on the enter).

**Comment by steve-perkins** [comment]
Generally we tend to err on the side of immutability (or as close as you can get with vanilla Java), and even use IDE plugins to encourage developers to do so.  However, I can imagine that practices may need to vary for code that is meant to ship as a public third-party library.

Can you please be a bit more specific about which classes you'd like to see `public`?  Or perhaps a sample unit test you might write if you weren't constrained by the `final` declarations?  Thanks!

**Comment by jentfoo** [comment]
> Generally we tend to err on the side of immutability 

I fail to see how making a CLASS as `final` has anything to do with immutability?  I am not trying to suggest making any variables non-final.

> Can you please be a bit more specific about which classes you'd like to see public

No concerns on visibility from me personally.  Though I do take a different philosophy from you (I tend to be on the side of leave many things protected so that developers can extend for special circumstances, at their own risk of course, and with an understanding that protected API's may change at any time).

>  Or perhaps a sample unit test you might write if you weren't constrained by the final declarations

In my unit tests I wanted to mock out `Logical` so that we would not have to use an actual vault store.  Because '`Logical` is `final` that is impossible to do without byte code manipulation.  So because of that I now have to resort to a wrapper class that holds a logical instance, but which I can now mock out.  In theory I think lots of parts of the library should be able to be mocked out.

**Comment by kunickiaj** [comment]
+1

Making classes final doesn't make them immutable, just prevents you from subclassing them (and preventing mocking without using tools like PowerMock).

**Comment by steve-perkins** [comment]
That was poorly phrased.  Marking VARIABLES as `final` is a partial step toward immutability (i.e. "or as close as you can get with vanilla Java")... but yes, applying `final` to classes and methods is another matter.

It's still a good practice for in-house code, because it signals that there was no original intent to subclass to override a class or method.  So if and when you find a reason for doing so, you have to think twice and change the declaration to show the updated intent.  It does makes unit testing more tricky, but that's why some methods in the codebase are `protected`... so they can be accessed in isolation by the unit test suite (which is in the same package).

However, after thinking about it some more, I do see how this is unduly burdensome for a third-party library, which people will be overriding with mocks for unit testing their own outside code.  So in the next version of the library... we will be keeping all of the `final` declarations for variables, but removing all of the `final` declarations applied to classes and methods.

The next version has been somewhat delayed... because one of the main features will be token renew, and the developer who's worked on the `auth` backend has been out on paternity leave with a new baby (see issue #5).  He just came back last Friday, and so we'll be talking about that in the week ahead.  If that work looks like it will take awhile, then I'll probably just push a new minor release this week with only the changed class and method declarations.

Thanks!

**Comment by jentfoo** [comment]
Awesome, I look forward to this (and even more so token renew!)

**Comment by steve-perkins** [comment]
This just went out with version 1.0.0.  It may take a few hours for Maven Central to sync and list it.
